[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd server && node server.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 100

[[deploy.ports]]
port = 3000
protocol = "http"

